# Generated by Django 6.0.1 on 2026-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
    ]
